version: "3.9"

services:
  db:
    image: postgres:14.2
    container_name: postgres-db
    restart: always
    environment: 
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=${DATABASE_NAMES}
    ports:
      - 5432:5432
    volumes:
      - data-volume:/var/lib/postgresql/data
      - ./postgres-init-scripts:/docker-entrypoint-initdb.d

volumes:
  data-volume: 
